# --- Connexion PostgreSQL ---
db.url=jdbc:postgresql://localhost:5432/bibliotheque_db
db.username=postgres
db.password=Hunter412
db.driver=org.postgresql.Driver

# --- Hibernate ---
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
